'use strict';

var staff = [
  {
    id: '25278',
    salutation: 'Ms',
    firstname: 'Leila',
    surname: 'Alali',
    email: 'lalali@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2013-07-15',
    house: 'Dwyer'
  },
  { id: '29679',
    salutation: 'Ms',
    firstname: 'Rosanna',
    surname: 'Algeri',
    email: 'ralgeri@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2015-01-19',
    house: 'O\'Connor'
  },
  { id: '13597',
    salutation: 'Mr',
    firstname: 'Patricio',
    surname: 'Alvarado',
    email: 'palvarado@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2012-01-27',
    house: 'Vaughan'
  },
  { id: '25920',
    salutation: 'Mrs',
    firstname: 'Sarah',
    surname: 'Alwan',
    email: 'salwan@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2013-09-30',
    house: 'McLaughlin'
  },
  { id: '11102',
    salutation: 'Mr',
    firstname: 'Justyn',
    surname: 'Ambrose',
    email: 'jambrose@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2010-01-27',
    house: 'O\'Connor'
  },
  { id: '4450',
    salutation: 'Ms',
    firstname: 'Rosemary',
    surname: 'Anderson',
    email: 'randerson@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2004-06-21',
    house: 'Cassidy'
  },
  { id: '13528',
    salutation: 'Mr',
    firstname: 'Luke',
    surname: 'Banboukjian',
    email: 'lbanboukjian@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2011-11-14',
    house: 'O\'Connor'
  },
  { id: '26428',
    salutation: 'Mrs',
    firstname: 'Melissa',
    surname: 'Barillaro',
    email: 'mbarillaro@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2014-01-28',
    house: 'Brady'
  },
  { id: '23227',
    salutation: 'Ms',
    firstname: 'Anastasia',
    surname: 'Batagianni',
    email: 'abatagianni@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'true',
    startDate: '2013-02-18',
    house: 'McLaughlin'
  },
  { id: '10036',
    salutation: 'Ms',
    firstname: 'Therese',
    surname: 'Bean',
    email: 'tbean@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2009-01-27',
    house: 'Delaney'
  },
  { id: '26234',
    salutation: 'Ms',
    firstname: 'Kate',
    surname: 'Beazley',
    email: 'kbeazley@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2014-01-23',
    house: 'O\'Connor'
  },
  { id: '32810',
    salutation: 'Mrs',
    firstname: 'Sandra',
    surname: 'Bentley',
    email: null,
    teacher: 'false',
    support: 'true',
    startDate: '2016-03-14',
    house: 'None'
  },
  { id: '21336',
    salutation: 'Mrs',
    firstname: 'Georgia',
    surname: 'Black',
    email: 'gblack@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2013-01-29',
    house: 'Vaughan'
  },
  { id: '21409',
    salutation: 'Mr',
    firstname: 'Paul',
    surname: 'Boon',
    email: 'pboon@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2013-01-29',
    house: 'O\'Connor'
  },
  { id: '26',
    salutation: 'Mrs',
    firstname: 'Leda',
    surname: 'Booth',
    email: 'lbooth@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '1991-02-07',
    house: 'Dwyer'
  },
  { id: '12251',
    salutation: 'Mr',
    firstname: 'Anthony',
    surname: 'Bosco',
    email: 'abosco@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2011-01-28',
    house: 'Delaney'
  },
  { id: '3054',
    salutation: 'Mrs',
    firstname: 'Leanne',
    surname: 'Brummell',
    email: 'lbrummell@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2006-01-23',
    house: 'Caulfield'
  },
  { id: '21411',
    salutation: 'Mrs',
    firstname: 'Linda',
    surname: 'Busetto',
    email: 'lbusetto@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2013-01-29',
    house: 'McLaughlin'
  },
  { id: '13529',
    salutation: 'Mr',
    firstname: 'Roberto',
    surname: 'Butera',
    email: 'rbutera@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2012-01-27',
    house: 'McLaughlin'
  },
  { id: '4240',
    salutation: 'Mr',
    firstname: 'Mark',
    surname: 'Capello',
    email: 'mcapello@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2004-03-17',
    house: 'McLaughlin'
  },
  { id: '32047',
    salutation: 'Mrs',
    firstname: 'Kylie',
    surname: 'Carroll',
    email: 'kcarroll@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2016-01-14',
    house: 'None'
  },
  { id: '25809',
    salutation: 'Mr',
    firstname: 'Greg',
    surname: 'Cashman',
    email: 'gcashman@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2014-01-23',
    house: 'Delaney'
  },
  { id: '13596',
    salutation: 'Ms',
    firstname: 'Bridgit',
    surname: 'Celler',
    email: 'bceller@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2012-01-27',
    house: 'Caulfield'
  },
  { id: '7845',
    salutation: 'Ms',
    firstname: 'Pippa',
    surname: 'Chan',
    email: 'pchan@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2006-05-01',
    house: 'Dwyer'
  },
  { id: '3560',
    salutation: 'Mrs',
    firstname: 'Louise',
    surname: 'Chiandotto',
    email: 'lchiandotto@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2003-01-29',
    house: 'Brady'
  },
  { id: '13174',
    salutation: 'Mr',
    firstname: 'Jeremy',
    surname: 'Cipolla',
    email: 'jcipolla@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2011-07-11',
    house: 'Vaughan'
  },
  { id: '31841',
    salutation: 'Miss',
    firstname: 'Belinda',
    surname: 'Clark',
    email: 'BClark@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'false',
    startDate: '2016-01-14',
    house: 'None'
  },
  { id: '3004',
    salutation: 'Miss',
    firstname: 'Eliza',
    surname: 'Cohen',
    email: 'ecohen@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2002-01-29',
    house: 'Brady'
  },
  { id: '26096',
    salutation: 'Mrs',
    firstname: 'Kim',
    surname: 'Cook',
    email: 'kcook@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2014-01-23',
    house: 'Caulfield'
  },
  { id: '31977',
    salutation: 'Mrs',
    firstname: 'Celinda',
    surname: 'Corsini',
    email: 'ccorsini@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2016-01-14',
    house: 'None'
  },
  { id: '10039',
    salutation: 'Mr',
    firstname: 'Ken',
    surname: 'Crossman',
    email: 'kcrossman@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2009-01-27',
    house: 'Caulfield'
  },
  { id: '31429',
    salutation: 'Mr',
    firstname: 'Nicholas',
    surname: 'De Bressac',
    email: 'ndebressac@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2016-01-14',
    house: 'None'
  },
  { id: '25957',
    salutation: 'Ms',
    firstname: 'Veronica',
    surname: 'de Jong',
    email: 'vdejong@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2014-01-23',
    house: 'O\'Connor'
  },
  { id: '32470',
    salutation: 'Ms',
    firstname: 'Minette Swales',
    surname: 'Denaro (Swales)',
    email: 'ddenaro@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2016-02-03',
    house: 'None'
  },
  { id: '10965',
    salutation: 'Ms',
    firstname: 'Lauren',
    surname: 'Di Marco',
    email: 'ldimarco@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2009-10-19',
    house: 'Vaughan'
  },
  { id: '32059',
    salutation: 'Mr',
    firstname: 'John',
    surname: 'Diakis (Diakopanagiotis)',
    email: 'jdiakis@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2016-01-14',
    house: 'None'
  },
  { id: '10762',
    salutation: 'Ms',
    firstname: 'Tracey',
    surname: 'Djurichkovic',
    email: 'tdjurichkovic@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2009-08-10',
    house: 'McLaughlin'
  },
  { id: '9731',
    salutation: 'Mr',
    firstname: 'Tim',
    surname: 'Douglas',
    email: 'tdouglas@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2008-09-01',
    house: 'Delaney'
  },
  { id: '31431',
    salutation: 'Mr',
    firstname: 'Michael',
    surname: 'Draper',
    email: 'mdraper@rosebank.nsw.edu.au ',
    teacher: 'false',
    support: 'false',
    startDate: '2015-07-27',
    house: 'None'
  },
  { id: '29775',
    salutation: 'Ms',
    firstname: 'Ava',
    surname: 'Du',
    email: 'adu@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2015-02-03',
    house: 'None'
  },
  { id: '9562',
    salutation: 'Mrs',
    firstname: 'Danielle',
    surname: 'Esterman',
    email: 'desterman@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2008-07-22',
    house: 'Cassidy'
  },
  { id: '11357',
    salutation: 'Mrs',
    firstname: 'Jessica',
    surname: 'Fallone',
    email: 'jfallone@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2010-04-19',
    house: 'Dwyer'
  },
  { id: '11422',
    salutation: 'Ms',
    firstname: 'Diane',
    surname: 'Falzon',
    email: 'dfalzon@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2010-05-11',
    house: 'Brady'
  },
  { id: '2475',
    salutation: 'Ms',
    firstname: 'Fiona',
    surname: 'Ford',
    email: 'fford@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2001-01-29',
    house: 'O\'Connor'
  },
  { id: '28165',
    salutation: 'Ms',
    firstname: 'Katie',
    surname: 'Foster',
    email: 'kfoster@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2014-07-14',
    house: 'Caulfield'
  },
  { id: '25987',
    salutation: 'Mrs',
    firstname: 'Melissa',
    surname: 'Gal',
    email: 'mgal@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2014-01-23',
    house: 'Vaughan'
  },
  { id: '7319',
    salutation: 'Mr',
    firstname: 'Tom',
    surname: 'Galea',
    email: 'galea@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2005-04-11',
    house: 'None'
  },
  { id: '11938',
    salutation: 'Ms',
    firstname: 'Sharon',
    surname: 'Gasparinatos',
    email: 'sgasparinatos@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2010-09-06',
    house: 'Dwyer'
  },
  { id: '8249',
    salutation: 'Ms',
    firstname: 'Louise',
    surname: 'Gentile',
    email: 'lgentile@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2007-04-23',
    house: 'McLaughlin'
  },
  { id: '32215',
    salutation: 'Mr',
    firstname: 'Michael',
    surname: 'Goldberg',
    email: 'mgoldberg@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2016-01-14',
    house: 'None'
  },
  { id: '7318',
    salutation: 'Ms',
    firstname: 'Rhonda',
    surname: 'Goodenough',
    email: 'rgoodenough@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2005-04-26',
    house: 'None'
  },
  { id: '7679',
    salutation: 'Mr',
    firstname: 'Tom',
    surname: 'Gould',
    email: 'tgould@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2006-01-30',
    house: 'Cassidy'
  },
  { id: '26014',
    salutation: 'Mrs',
    firstname: 'Bronwyn',
    surname: 'Gow',
    email: 'bgow@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2014-01-23',
    house: 'Dwyer'
  },
  { id: '30291',
    salutation: 'Mr',
    firstname: 'Timothy',
    surname: 'Grammer',
    email: 'tgrammer@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2015-03-16',
    house: 'None'
  },
  { id: '26313',
    salutation: 'Miss',
    firstname: 'Dani',
    surname: 'Green',
    email: 'dgreen@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2014-01-23',
    house: 'Dwyer'
  },
  { id: '55',
    salutation: 'Mrs',
    firstname: 'Cathy',
    surname: 'Grima',
    email: 'cgrima@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '1989-01-30',
    house: 'Delaney'
  },
  { id: '7534',
    salutation: 'Mrs',
    firstname: 'Diana',
    surname: 'Guerra',
    email: 'dguerra@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2005-08-08',
    house: 'Delaney'
  },
  { id: '4085',
    salutation: 'Mrs',
    firstname: 'Rodana',
    surname: 'Habib',
    email: 'rhabib@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2011-05-27',
    house: 'None'
  },
  { id: '25983',
    salutation: 'Mr',
    firstname: 'Phillip',
    surname: 'Hammond',
    email: 'phammond@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2014-01-23',
    house: 'Caulfield'
  },
  { id: '11104',
    salutation: 'Mr',
    firstname: 'Paul',
    surname: 'Hardwick',
    email: 'phardwick@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2010-01-27',
    house: 'McLaughlin'
  },
  { id: '11936',
    salutation: 'Ms',
    firstname: 'Imanta',
    surname: 'Harris',
    email: 'iharris@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2010-08-13',
    house: 'Vaughan'
  },
  { id: '11259',
    salutation: 'Ms',
    firstname: 'Stephanie',
    surname: 'Harris',
    email: 'sharris@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2010-03-02',
    house: 'Cassidy'
  },
  { id: '12219',
    salutation: 'Mr',
    firstname: 'Michael',
    surname: 'Heiniger',
    email: 'mheiniger@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2010-12-06',
    house: 'Cassidy'
  },
  { id: '4255',
    salutation: 'Mrs',
    firstname: 'Melinda',
    surname: 'Henderson',
    email: 'mhenderson@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2004-04-27',
    house: 'Delaney'
  },
  { id: '32173',
    salutation: 'Mrs',
    firstname: 'Kelly',
    surname: 'Hollis',
    email: 'khollis@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2016-01-14',
    house: 'None'
  },
  { id: '30620',
    salutation: 'Ms',
    firstname: 'Aviva',
    surname: 'Hyams',
    email: 'ahyams@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2015-08-10',
    house: 'None'
  },
  { id: '29797',
    salutation: 'Mrs',
    firstname: 'Karen',
    surname: 'James',
    email: 'kjames@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'false',
    startDate: '2015-02-06',
    house: 'None'
  },
  { id: '14000',
    salutation: 'Mr',
    firstname: 'James',
    surname: 'Jeffery',
    email: 'jjeffery@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2012-05-07',
    house: 'Delaney'
  },
  { id: '8721',
    salutation: 'Ms',
    firstname: 'Katherine',
    surname: 'Johnson',
    email: 'kjohnson@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2014-03-12',
    house: 'Cassidy'
  },
  { id: '21410',
    salutation: 'Miss',
    firstname: 'Cheryl',
    surname: 'Jones',
    email: 'cjones@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2013-01-25',
    house: 'Dwyer'
  },
  { id: '2041',
    salutation: 'Mrs',
    firstname: 'Regina',
    surname: 'Kaminska',
    email: 'rkaminska@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2000-03-27',
    house: 'None'
  },
  { id: '26314',
    salutation: 'Ms',
    firstname: 'Maria',
    surname: 'Karadimas',
    email: 'mkaradimas@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2014-01-28',
    house: 'Vaughan'
  },
  { id: '39',
    salutation: 'Mrs',
    firstname: 'Rita',
    surname: 'Khoury',
    email: 'rkhoury@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '1982-02-02',
    house: 'None'
  },
  { id: '10551',
    salutation: 'Miss',
    firstname: 'Lina',
    surname: 'Kim',
    email: 'lkim@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2009-05-11',
    house: 'None'
  },
  { id: '17',
    salutation: 'Mr',
    firstname: 'Garry',
    surname: 'King',
    email: 'gking@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '1993-01-21',
    house: 'Caulfield'
  },
  { id: '28109',
    salutation: 'Ms',
    firstname: 'Kate',
    surname: 'Kovic',
    email: 'kkovic@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2014-07-14',
    house: 'Vaughan'
  },
  { id: '8436',
    salutation: 'Mr',
    firstname: 'Peter',
    surname: 'Kuo',
    email: 'pkuo@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2007-07-30',
    house: 'Delaney'
  },
  { id: '26408',
    salutation: 'Ms',
    firstname: 'Marinella',
    surname: 'La Robina',
    email: 'mlarobina@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2014-01-28',
    house: 'Brady'
  },
  { id: '26028',
    salutation: 'Mrs',
    firstname: 'Stacey',
    surname: 'Laffan',
    email: 'slaffan@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2014-01-23',
    house: 'McLaughlin'
  },
  { id: '23406',
    salutation: 'Dr',
    firstname: 'Liz',
    surname: 'Lamb',
    email: 'elamb@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'false',
    startDate: '2013-03-05',
    house: 'None'
  },
  { id: '8121',
    salutation: 'Mrs',
    firstname: 'Annalicia',
    surname: 'Latham',
    email: 'alatham@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2007-01-29',
    house: 'Brady'
  },
  { id: '22571',
    salutation: 'Mr',
    firstname: 'Brendan',
    surname: 'Lee',
    email: 'blee@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2013-02-22',
    house: 'Caulfield'
  },
  { id: '12619',
    salutation: 'Ms',
    firstname: 'Mariette',
    surname: 'Lethbridge',
    email: 'mlethbridge@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2011-04-27',
    house: 'Brady'
  },
  { id: '30109',
    salutation: 'Ms',
    firstname: 'Erini',
    surname: 'Limnatites',
    email: 'elimnatites@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2015-03-06',
    house: 'None'
  },
  { id: '12178',
    salutation: 'Mr',
    firstname: 'Ken',
    surname: 'Lin',
    email: 'klin@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2010-11-16',
    house: 'Caulfield'
  },
  { id: '31890',
    salutation: 'Mr',
    firstname: 'Kristopher',
    surname: 'Little',
    email: 'kristopherlittle@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2015-10-08',
    house: 'None'
  },
  { id: '31878',
    salutation: 'Mrs',
    firstname: 'Kirsten',
    surname: 'Livie-Primero',
    email: 'klivieprimero@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2015-10-06',
    house: 'None'
  },
  { id: '16',
    salutation: 'Mr',
    firstname: 'Alfred',
    surname: 'Lobo',
    email: 'alobo@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '1994-01-31',
    house: 'Caulfield'
  },
  { id: '22635',
    salutation: 'Mr',
    firstname: 'Ben',
    surname: 'Lomnicki',
    email: 'blomnicki@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2013-01-29',
    house: 'Cassidy'
  },
  { id: '21555',
    salutation: 'Mrs',
    firstname: 'Susan',
    surname: 'Lotter',
    email: 'slotter@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2013-01-29',
    house: 'Vaughan'
  },
  { id: '3005',
    salutation: 'Mrs',
    firstname: 'Maree',
    surname: 'Lucas',
    email: 'mlucas@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2002-01-29',
    house: 'Cassidy'
  },
  { id: '31430',
    salutation: 'Mr',
    firstname: 'Paul',
    surname: 'Lumley',
    email: 'plumley@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'false',
    startDate: '2015-07-27',
    house: 'None'
  },
  { id: '32055',
    salutation: 'Mrs',
    firstname: 'Paula',
    surname: 'Mahony',
    email: 'pmahony@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2016-01-19',
    house: 'None'
  },
  { id: '21408',
    salutation: 'Mrs',
    firstname: 'Emma',
    surname: 'Marshall',
    email: 'emarshall@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2013-01-29',
    house: 'None'
  },
  { id: '9654',
    salutation: 'Mrs',
    firstname: 'Jacquelene',
    surname: 'Mastroianni',
    email: 'jmastroianni@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2009-10-19',
    house: 'Delaney'
  },
  { id: '25982',
    salutation: 'Mr',
    firstname: 'Peter',
    surname: 'Mavritsakis',
    email: 'pmavritsakis@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2014-01-23',
    house: 'None'
  },
  { id: '10870',
    salutation: 'Mrs',
    firstname: 'Tina',
    surname: 'Mavritsakis',
    email: 'tmavritsakis@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2009-09-07',
    house: 'O\'Connor'
  },
  { id: '52',
    salutation: 'Ms',
    firstname: 'Kathy',
    surname: 'McAloon',
    email: 'kmcaloon@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '1995-01-30',
    house: 'Cassidy'
  },
  { id: '12053',
    salutation: 'Ms',
    firstname: 'Elise',
    surname: 'McKenzie',
    email: 'emckenzie@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2010-10-11',
    house: 'Delaney'
  },
  { id: '32175',
    salutation: 'Mrs',
    firstname: 'Philomena',
    surname: 'Middeldorp',
    email: 'pmiddeldorp@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2016-01-14',
    house: 'None'
  },
  { id: '13444',
    salutation: 'Ms',
    firstname: 'Rhiannon',
    surname: 'Mitchell',
    email: 'rmitchell@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2012-07-16',
    house: 'McLaughlin'
  },
  { id: '59',
    salutation: 'Mrs',
    firstname: 'Maria',
    surname: 'Mollace',
    email: 'mmollace@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '1995-04-03',
    house: 'None'
  },
  { id: '6',
    salutation: 'Mrs',
    firstname: 'Maria',
    surname: 'Mollica',
    email: 'mmollica@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '1989-07-12',
    house: 'McLaughlin'
  },
  { id: '13592',
    salutation: 'Ms',
    firstname: 'Claire',
    surname: 'Moran',
    email: 'cmoran@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2012-01-27',
    house: 'Delaney'
  },
  { id: '25986',
    salutation: 'Mr',
    firstname: 'Pedro',
    surname: 'Moreira',
    email: 'pmoreira@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2014-01-23',
    house: 'O\'Connor'
  },
  { id: '21413',
    salutation: 'Ms',
    firstname: 'Clare',
    surname: 'Mullen',
    email: 'cmullen@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2013-01-29',
    house: 'Caulfield'
  },
  { id: '28836',
    salutation: 'Ms',
    firstname: 'Jade',
    surname: 'Munro',
    email: 'jmunro@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2015-01-20',
    house: 'None'
  },
  { id: '24846',
    salutation: 'Mrs',
    firstname: 'Mary',
    surname: 'Mura',
    email: 'mmura@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2013-05-20',
    house: 'McLaughlin'
  },
  { id: '11161',
    salutation: 'Ms',
    firstname: 'Melanie',
    surname: 'Nelson',
    email: 'mnelson@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2010-02-01',
    house: 'Vaughan'
  },
  { id: '32526',
    salutation: 'Dr',
    firstname: 'Michelle',
    surname: 'Nemec',
    email: 'mnemec@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2016-01-27',
    house: 'None'
  },
  { id: '25984',
    salutation: 'Ms',
    firstname: 'Amy',
    surname: 'Neylan',
    email: 'aneylan@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2014-01-23',
    house: 'None'
  },
  { id: '12215',
    salutation: 'Dr',
    firstname: 'Paul',
    surname: 'O\'Shea',
    email: 'poshea@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2011-01-28',
    house: 'Dwyer'
  },
  { id: '33',
    salutation: 'Ms',
    firstname: 'Jackie',
    surname: 'Oh',
    email: 'joh@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '1992-01-28',
    house: 'Cassidy'
  },
  { id: '30622',
    salutation: 'Ms',
    firstname: 'Kim',
    surname: 'Palmer',
    email: 'kpalmer@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2015-05-18',
    house: 'None'
  },
  { id: '21628',
    salutation: 'Ms',
    firstname: 'Annie',
    surname: 'Park',
    email: 'apark@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2013-01-29',
    house: 'Delaney'
  },
  { id: '4286',
    salutation: 'Ms',
    firstname: 'Angie',
    surname: 'Parthenis',
    email: 'aparthenis@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2004-04-27',
    house: 'O\'Connor'
  },
  { id: '3884',
    salutation: 'Mrs',
    firstname: 'Angela',
    surname: 'Pavicic',
    email: 'apavicic@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2003-06-10',
    house: 'None'
  },
  { id: '31602',
    salutation: 'Ms',
    firstname: 'Darrelle',
    surname: 'Pendle',
    email: 'dpendle@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2015-10-06',
    house: 'None'
  },
  { id: '54',
    salutation: 'Miss',
    firstname: 'Lidia',
    surname: 'Peruzzi',
    email: 'lperuzzi@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '1986-01-28',
    house: 'McLaughlin'
  },
  { id: '31607',
    salutation: 'Ms',
    firstname: 'Lara',
    surname: 'Picone',
    email: 'lpicone@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2016-02-16',
    house: 'None'
  },
  { id: '31975',
    salutation: 'Mr',
    firstname: 'Jake',
    surname: 'Plaskett',
    email: 'JPlaskett@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2016-01-14',
    house: 'None'
  },
  { id: '26117',
    salutation: 'Ms',
    firstname: 'Kate',
    surname: 'Plokstys',
    email: 'kplokstys@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2014-01-23',
    house: 'Dwyer'
  },
  { id: '9239',
    salutation: 'Ms',
    firstname: 'Anna',
    surname: 'Prentice',
    email: 'aprentice@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2008-04-28',
    house: 'None'
  },
  { id: '26540',
    salutation: 'Ms',
    firstname: 'Veronica',
    surname: 'Presser',
    email: 'vpresser@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2014-03-03',
    house: 'O\'Connor'
  },
  { id: '29657',
    salutation: 'Ms',
    firstname: 'Jessica',
    surname: 'Quarmby',
    email: 'jquarmby@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2015-01-20',
    house: 'O\'Connor'
  },
  { id: '32550',
    salutation: 'Mr',
    firstname: 'Nicola',
    surname: 'Raucci',
    email: 'nraucci@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'false',
    startDate: '2016-01-27',
    house: 'None'
  },
  { id: '32287',
    salutation: 'Mrs',
    firstname: 'Paula',
    surname: 'Reed',
    email: 'preed@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2016-01-14',
    house: 'None'
  },
  { id: '12227',
    salutation: 'Ms',
    firstname: 'Maria',
    surname: 'Ribeiro',
    email: 'mribeiro@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2010-12-13',
    house: 'Dwyer'
  },
  { id: '30290',
    salutation: 'Mr',
    firstname: 'Bryan',
    surname: 'Roddie',
    email: 'broddie@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2016-01-14',
    house: 'None'
  },
  { id: '13414',
    salutation: 'Mrs',
    firstname: 'Connie',
    surname: 'Ross',
    email: 'cross@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2011-10-10',
    house: 'O\'Connor'
  },
  { id: '8365',
    salutation: 'Mr',
    firstname: 'Vere',
    surname: 'Rozario',
    email: 'vrozario@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2007-06-18',
    house: 'Vaughan'
  },
  { id: '32049',
    salutation: 'Mr',
    firstname: 'Saif',
    surname: 'Samaan',
    email: 'ssamaan@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2015-12-07',
    house: 'None'
  },
  { id: '845',
    salutation: 'Mrs',
    firstname: 'Megan',
    surname: 'Sato',
    email: 'msato@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '1996-01-29',
    house: 'None'
  },
  { id: '8231',
    salutation: 'Mr',
    firstname: 'Peter',
    surname: 'Scalia',
    email: 'pscalia@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2007-03-19',
    house: 'Dwyer'
  },
  { id: '11719',
    salutation: 'Ms',
    firstname: 'Fabienne',
    surname: 'Scott',
    email: 'fscott@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2010-07-19',
    house: 'Dwyer'
  },
  { id: '10578',
    salutation: 'Ms',
    firstname: 'Joan',
    surname: 'Sinclair',
    email: 'jsinclair@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2009-05-15',
    house: 'Vaughan'
  },
  { id: '51',
    salutation: 'Mrs',
    firstname: 'Joanne',
    surname: 'Slaney',
    email: 'jslaney@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '1995-01-30',
    house: 'Dwyer'
  },
  { id: '24279',
    salutation: 'Mr',
    firstname: 'Jason',
    surname: 'Smith',
    email: 'jsmith@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2013-04-12',
    house: 'Cassidy'
  },
  { id: '32093',
    salutation: 'Mrs',
    firstname: 'Susan',
    surname: 'Stenner',
    email: 'sstenner@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2016-01-14',
    house: 'None'
  },
  { id: '13600',
    salutation: 'Ms',
    firstname: 'Rebecca',
    surname: 'Stooke',
    email: 'rstooke@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2012-01-27',
    house: 'Delaney'
  },
  { id: '13175',
    salutation: 'Mr',
    firstname: 'Tim',
    surname: 'Tan',
    email: 'ttan@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2011-07-11',
    house: 'Cassidy'
  },
  { id: '10041',
    salutation: 'Mr',
    firstname: 'Anthony',
    surname: 'Taylor',
    email: 'ataylor@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2009-01-27',
    house: 'Delaney'
  },
  { id: '29526',
    salutation: 'Miss',
    firstname: 'Angela',
    surname: 'Tillott',
    email: 'atillott@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2015-01-20',
    house: 'Brady'
  },
  { id: '12216',
    salutation: 'Ms',
    firstname: 'Claudia',
    surname: 'Vayda',
    email: 'cvayda@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2011-01-28',
    house: 'O\'Connor'
  },
  { id: '28807',
    salutation: 'Mr',
    firstname: 'Harry',
    surname: 'Vomvellis',
    email: 'hvomvellis@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2015-01-20',
    house: 'Caulfield'
  },
  { id: '12226',
    salutation: 'Mr',
    firstname: 'Matthew',
    surname: 'White',
    email: 'mwhite@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2011-01-28',
    house: 'Brady'
  },
  { id: '30730',
    salutation: 'Mr',
    firstname: 'Jerry',
    surname: 'Wong',
    email: 'jwong@rosebank.nsw.edu.au',
    teacher: 'false',
    support: 'true',
    startDate: '2015-05-14',
    house: 'None'
  },
  { id: '13544',
    salutation: 'Mr',
    firstname: 'Mark',
    surname: 'Zilich',
    email: 'mzilich@rosebank.nsw.edu.au',
    teacher: 'true',
    support: 'false',
    startDate: '2012-01-27',
    house: 'None'
  }
];

module.exports = staff;
